version: "3.3"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'django'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    expose:
      # Opens port 3306 on the container
      - '3306'

volumes:
  db_data: