# Generated by Django 4.1.3 on 2022-12-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Başlık Bilgisi Burada Girilir.', max_length=100, null=True, verbose_name='Başlık Giriniz')),
                ('content', models.TextField(max_length=1000, null=True, verbose_name='İçerik Giriniz')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
