# Generated by Django 4.1.3 on 2022-12-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='İsim Bilgisi Burada Girilir.', max_length=50, null=True, verbose_name='İsim Giriniz')),
                ('surname', models.CharField(help_text='Soyisim Bilgisi Burada Girilir.', max_length=50, null=True, verbose_name='Soyisim Giriniz')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Email Giriniz')),
                ('email2', models.EmailField(max_length=50, null=True, verbose_name="Email'i tekrar giriniz")),
                ('content', models.TextField(help_text='İçerik Bilgisi Burada Girilir.', max_length=50, null=True, verbose_name='İçerik giriniz')),
            ],
            options={
                'verbose_name': 'Registration',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.URLField(max_length=1000, null=True, verbose_name='Bağlantı adresini giriniz'),
        ),
    ]
