# Generated by Django 4.1.3 on 2022-12-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact_blog_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Resim Yükleyiniz'),
        ),
    ]
