# Generated by Django 4.1.3 on 2022-12-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_image_alter_blog_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category_choices',
            field=models.CharField(choices=[('art', 'ART'), ('science', 'SCIENCE'), ('sports', 'SPORTS'), ('photography', 'PHOTOGRAPHY'), ('technology', 'TECHNOLOGY'), ('travel', 'TRAVEL'), ('other', 'OTHER')], default='other', help_text='Kategori ', max_length=20, verbose_name='Kategori Seçiniz'),
        ),
    ]
