# Generated by Django 4.1.3 on 2022-12-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_category_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='category_choices',
            field=models.CharField(choices=[(None, 'Please choice an option'), ('art', 'ART'), ('science', 'SCIENCE'), ('sports', 'SPORTS'), ('photography', 'PHOTOGRAPHY'), ('technology', 'TECHNOLOGY'), ('travel', 'TRAVEL'), ('other', 'OTHER')], help_text='Kategori ', max_length=20, null=True, verbose_name='Kategori Seçiniz'),
        ),
    ]
