# Generated by Django 4.1.3 on 2022-12-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_category_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category_choices',
            field=models.CharField(choices=[(None, 'Please select an option'), ('art', 'ART'), ('science', 'SCIENCE'), ('sports', 'SPORTS'), ('photography', 'PHOTOGRAPHY'), ('technology', 'TECHNOLOGY'), ('travel', 'TRAVEL'), ('other', 'OTHER')], help_text='Kategori ', max_length=20, null=True, verbose_name='Kategori Seçiniz'),
        ),
    ]
