# Generated by Django 4.1.3 on 2022-12-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(max_length=1000, null=True, verbose_name='İçerik Giriniz'),
        ),
    ]
