# Generated by Django 4.1.3 on 2022-12-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Comments'},
        ),
    ]
