# Generated by Django 4.1.3 on 2022-12-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_comment_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Comments'},
        ),
    ]
