# Generated by Django 4.1.3 on 2022-12-24 02:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category_choices',
            field=models.CharField(choices=[(None, 'Please select an option'), ('art', 'ART'), ('science', 'SCIENCE'), ('sports', 'SPORTS'), ('photography', 'PHOTOGRAPHY'), ('technology', 'TECHNOLOGY'), ('travel', 'TRAVEL'), ('other', 'OTHER')], help_text='Select a category for your blog', max_length=20, null=True, verbose_name='Select a Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=5000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/default_img.jpg', help_text='Load an image for your blog', null=True, upload_to='', verbose_name='Load an image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True, help_text='Link of the blog', max_length=1000, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Title of the blog', max_length=100, null=True, verbose_name='Title'),
        ),
    ]
