# Generated by Django 4.1.3 on 2022-12-20 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_tag_created_at_remove_tag_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(null=True, to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='Tag Name'),
            preserve_default=False,
        ),
    ]
