# Generated by Django 4.1.3 on 2022-12-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_tag_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
