# Generated by Django 4.1.3 on 2022-12-21 01:30

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0028_remove_blog_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='new_field',
            field=models.CharField(default='DEFAULT VALUE', max_length=140),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category_choices',
            field=models.CharField(choices=[(None, 'Please select an option'), ('art', 'ART'), ('science', 'SCIENCE'), ('sports', 'SPORTS'), ('photography', 'PHOTOGRAPHY'), ('technology', 'TECHNOLOGY'), ('travel', 'TRAVEL'), ('other', 'OTHER')], help_text='Select a category for your blog', max_length=20, null=True, verbose_name='Select a Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(help_text='Description of the blog', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/default_img.jpg', help_text='Load an image for your blog', null=True, upload_to='', verbose_name='Load an image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True, help_text='Link of the blog', max_length=1000, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Title of the blog', max_length=100, null=True, verbose_name='Title'),
        ),
    ]
