# Generated by Django 4.1.3 on 2022-12-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_blog_tags_alter_blog_category_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
