# Generated by Django 4.1.3 on 2022-12-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_blog_new_field_blog_tags_alter_blog_category_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='new_field',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='DEFAULT VALUE', max_length=100, unique=True),
        ),
    ]
