# Generated by Django 4.1.3 on 2022-12-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_remove_blog_new_field_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='new_field',
            field=models.CharField(default='DEFAULT VALUE', max_length=140),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
