# Generated by Django 4.1.3 on 2022-12-23 21:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Description of the blog', max_length=5000, null=True, verbose_name='Description'),
        ),
    ]
