# Generated by Django 4.1.3 on 2022-12-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_blog_new_field_alter_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
