# Generated by Django 4.1.3 on 2022-12-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_remove_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='new_field',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug of the blog', max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
